package com.easy.query.test.entity.base;

import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.test.entity.Topic;

/**
 * this file automatically generated by easy-query, don't modify it
 *
 * @author xuejiaming
 */
public class TopicTestProxy extends AbstractProxyEntity<TopicTestProxy, Topic> {

    public static TopicTestProxy createTable() {
        return new TopicTestProxy();
    }
    private static final Class<Topic> entityClass = Topic.class;

    private TopicTestProxy() {

    }

    public SQLColumn<TopicTestProxy,String> id(){
        return get("id");
    }
    public SQLColumn<TopicTestProxy,String> title(){
        return get("title");
    }

    @Override
    public Class<Topic> getEntityClass() {
        return entityClass;
    }

}