package com.easy.query.test.entity.base;

import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.test.entity.Topic;

import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query, don't modify it
 *
 * @author xuejiaming
 */
public class TopicTestProxy extends AbstractProxyEntity<TopicTestProxy, Topic> {

    public static TopicTestProxy createTable() {
        return new TopicTestProxy();
    }

    private static final Class<Topic> entityClass = Topic.class;
//    public static final PropColumn id = new SQLPropColumn("id");
//    public static final PropColumn title = new SQLPropColumn("title");

    public TopicTestProxy() {

    }

    public SQLColumn<TopicTestProxy, String> id() {
        return get("id");
    }

    public SQLColumn<TopicTestProxy, String> title() {
        return get("title");
    }

    public SQLColumn<TopicTestProxy, Integer> stars() {
        return get("stars");
    }

    public SQLColumn<TopicTestProxy, LocalDateTime> createTime() {
        return get("createTime");
    }

    @Override
    public Class<Topic> getEntityClass() {
        return entityClass;
    }

}