package com.easy.query.test.dto;


import com.easy.query.test.entity.MyCategory;
import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.util.List;

import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.MyCategory }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class MyCategoryDTO {


    private String id;
    private String parentId;
    private String name;

    @Navigate(value = RelationTypeEnum.OneToMany,selfProperty = "id",targetProperty = "parentId",supportNonEntity = true)
    private List<MyCategoryDTO> children;

}
