package com.easy.query.test.dto;


import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.school.SchoolClassAggregate }
 *
 * @author easy-query
 */
@Data
public class SchoolClassAggregateDTO {


    private String id;
    private String name;
    private Long studentSize;


}
