package com.easy.query.test.dto;


import com.easy.query.core.annotation.Column;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.UserExtra }
 *
 * @author easy-query
 */
@Data
public class UserExtraDTO {


    private String id;
    private String firstName;
    private String lastName;
    private LocalDateTime birthday;
    private String fullName;
    private Integer age;


}
