package com.easy.query.test.entity.blogtest.dto;


import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.util.List;
import java.time.LocalDateTime;
import java.util.stream.Collectors;

import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.blogtest.SysUser }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class SysUserWithRoleAndMenuDTO {


    private String id;
    private String name;
    private Integer age;
    private LocalDateTime createTime;
    @Navigate(value = RelationTypeEnum.ManyToMany)
    private List<InternalRoles> roles;



    public List<InternalMenus> getMenus(){

        return roles.stream().flatMap(r->r.getMenus().stream()).collect(Collectors.toList());
    }


    /**
     * {@link com.easy.query.test.entity.blogtest.SysMenu }
     *
     */
    @Data
    public static class InternalMenus {

        private String id;
        private String name;
        private String route;
        private String icon;
        private LocalDateTime createTime;


    }


    /**
     * {@link com.easy.query.test.entity.blogtest.SysRole }
     *
     */
    @Data
    public static class InternalRoles {

        private String id;
        private String name;
        private LocalDateTime createTime;
        @JsonIgnore
        @Navigate(value = RelationTypeEnum.ManyToMany)
        private List<InternalMenus> menus;


    }

}
