package com.easy.query.test.entity.school.proxy;

import com.easy.query.core.expression.parser.core.available.TableAvailable;
import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.proxy.core.EntitySQLContext;
import com.easy.query.test.entity.school.SchoolClassAggregate;
import com.easy.query.core.proxy.columns.SQLStringColumn;
import com.easy.query.core.proxy.columns.SQLNavigateColumn;
import com.easy.query.core.proxy.columns.SQLQueryable;
import com.easy.query.core.proxy.columns.SQLAnyColumn;
import com.easy.query.core.proxy.columns.SQLNumberColumn;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 * 如果出现属性冲突请使用@ProxyProperty进行重命名
 *
 * @author easy-query
 */
public class SchoolClassAggregateProxy extends AbstractProxyEntity<SchoolClassAggregateProxy, SchoolClassAggregate> {

    private static final Class<SchoolClassAggregate> entityClass = SchoolClassAggregate.class;

    public static SchoolClassAggregateProxy createTable() {
        return new SchoolClassAggregateProxy();
    }

    public SchoolClassAggregateProxy() {
    }

    /**
     * {@link SchoolClassAggregate#getId}
     */
    public SQLStringColumn<SchoolClassAggregateProxy, java.lang.String> id() {
        return getStringColumn("id", java.lang.String.class);
    }

    /**
     * {@link SchoolClassAggregate#getName}
     */
    public SQLStringColumn<SchoolClassAggregateProxy, java.lang.String> name() {
        return getStringColumn("name", java.lang.String.class);
    }

    /**
     * 一对多 一个班级多个学生
     * {@link SchoolClassAggregate#getSchoolStudents}
     */
    public SQLQueryable<com.easy.query.test.entity.school.proxy.SchoolStudentProxy, com.easy.query.test.entity.school.SchoolStudent> schoolStudents() {
        return getNavigates("schoolStudents", new com.easy.query.test.entity.school.proxy.SchoolStudentProxy());
    }

    /**
     * {@link SchoolClassAggregate#getStudentSize}
     */
    public SQLNumberColumn<SchoolClassAggregateProxy, java.lang.Long> studentSize() {
        return getNumberColumn("studentSize", java.lang.Long.class);
    }


    @Override
    public Class<SchoolClassAggregate> getEntityClass() {
        return entityClass;
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public SchoolClassAggregateProxyFetcher FETCHER = new SchoolClassAggregateProxyFetcher(this, null, SQLSelectAsExpression.empty);


    public static class SchoolClassAggregateProxyFetcher extends AbstractFetcher<SchoolClassAggregateProxy, SchoolClassAggregate, SchoolClassAggregateProxyFetcher> {

        public SchoolClassAggregateProxyFetcher(SchoolClassAggregateProxy proxy, SchoolClassAggregateProxyFetcher prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * {@link SchoolClassAggregate#getId}
         */
        public SchoolClassAggregateProxyFetcher id() {
            return add(getProxy().id());
        }

        /**
         * {@link SchoolClassAggregate#getName}
         */
        public SchoolClassAggregateProxyFetcher name() {
            return add(getProxy().name());
        }

        /**
         * {@link SchoolClassAggregate#getStudentSize}
         */
        public SchoolClassAggregateProxyFetcher studentSize() {
            return add(getProxy().studentSize());
        }


        @Override
        protected SchoolClassAggregateProxyFetcher createFetcher(SchoolClassAggregateProxy cp, AbstractFetcher<SchoolClassAggregateProxy, SchoolClassAggregate, SchoolClassAggregateProxyFetcher> prev, SQLSelectAsExpression sqlSelectExpression) {
            return new SchoolClassAggregateProxyFetcher(cp, this, sqlSelectExpression);
        }
    }

}
