package com.easy.query.test.entity.proxy;

import com.easy.query.core.expression.parser.core.available.TableAvailable;
import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.SQLColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.proxy.core.EntitySQLContext;
import com.easy.query.test.entity.TopicTypeArrayJsonJackson;
import com.easy.query.core.proxy.columns.types.SQLStringTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLIntegerTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLAnyTypeColumn;
import com.easy.query.core.proxy.columns.types.SQLLocalDateTimeTypeColumn;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 * 如果出现属性冲突请使用@ProxyProperty进行重命名
 *
 * @author easy-query
 */
public class TopicTypeArrayJsonJacksonProxy extends AbstractProxyEntity<TopicTypeArrayJsonJacksonProxy, TopicTypeArrayJsonJackson> {

    private static final Class<TopicTypeArrayJsonJackson> entityClass = TopicTypeArrayJsonJackson.class;

    public static final TopicTypeArrayJsonJacksonProxy TABLE = createTable().createEmpty();

    public static TopicTypeArrayJsonJacksonProxy createTable() {
        return new TopicTypeArrayJsonJacksonProxy();
    }

    public TopicTypeArrayJsonJacksonProxy() {
    }

    /**
     * {@link TopicTypeArrayJsonJackson#getId}
     */
    public SQLStringTypeColumn<TopicTypeArrayJsonJacksonProxy> id() {
        return getStringTypeColumn("id");
    }

    /**
     * {@link TopicTypeArrayJsonJackson#getStars}
     */
    public SQLIntegerTypeColumn<TopicTypeArrayJsonJacksonProxy> stars() {
        return getIntegerTypeColumn("stars");
    }

    /**
     * {@link TopicTypeArrayJsonJackson#getTitle}
     */
    public SQLAnyTypeColumn<TopicTypeArrayJsonJacksonProxy, com.easy.query.test.entity.TopicTypeJsonValue> title() {
        return getAnyTypeColumn("title", __cast(Object.class));
    }


    /**
     * {@link TopicTypeArrayJsonJackson#getTitle2}
     */
    public SQLAnyTypeColumn<TopicTypeArrayJsonJacksonProxy, java.util.List<com.easy.query.test.entity.TopicTypeJsonValue>> title2() {
        return getAnyTypeColumn("title2", __cast(Object.class));
    }


    /**
     * private Integer[] title3;
     * {@link TopicTypeArrayJsonJackson#getTopicType}
     */
    public SQLIntegerTypeColumn<TopicTypeArrayJsonJacksonProxy> topicType() {
        return getIntegerTypeColumn("topicType");
    }

    /**
     * {@link TopicTypeArrayJsonJackson#getCreateTime}
     */
    public SQLLocalDateTimeTypeColumn<TopicTypeArrayJsonJacksonProxy> createTime() {
        return getLocalDateTimeTypeColumn("createTime");
    }


    @Override
    public Class<TopicTypeArrayJsonJackson> getEntityClass() {
        return entityClass;
    }

    @Override
    public TopicTypeArrayJsonJacksonProxy createNew() {
        return createTable();
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public TopicTypeArrayJsonJacksonProxyFetcher FETCHER = new TopicTypeArrayJsonJacksonProxyFetcher(this, null, SQLSelectAsExpression.empty);


    public static class TopicTypeArrayJsonJacksonProxyFetcher extends AbstractFetcher<TopicTypeArrayJsonJacksonProxy, TopicTypeArrayJsonJackson, TopicTypeArrayJsonJacksonProxyFetcher> {

        public TopicTypeArrayJsonJacksonProxyFetcher(TopicTypeArrayJsonJacksonProxy proxy, TopicTypeArrayJsonJacksonProxyFetcher prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * {@link TopicTypeArrayJsonJackson#getId}
         */
        public TopicTypeArrayJsonJacksonProxyFetcher id() {
            return add(getProxy().id());
        }

        /**
         * {@link TopicTypeArrayJsonJackson#getStars}
         */
        public TopicTypeArrayJsonJacksonProxyFetcher stars() {
            return add(getProxy().stars());
        }

        /**
         * {@link TopicTypeArrayJsonJackson#getTitle}
         */
        public TopicTypeArrayJsonJacksonProxyFetcher title() {
            return add(getProxy().title());
        }

        /**
         * {@link TopicTypeArrayJsonJackson#getTitle2}
         */
        public TopicTypeArrayJsonJacksonProxyFetcher title2() {
            return add(getProxy().title2());
        }

        /**
         * private Integer[] title3;
         * {@link TopicTypeArrayJsonJackson#getTopicType}
         */
        public TopicTypeArrayJsonJacksonProxyFetcher topicType() {
            return add(getProxy().topicType());
        }

        /**
         * {@link TopicTypeArrayJsonJackson#getCreateTime}
         */
        public TopicTypeArrayJsonJacksonProxyFetcher createTime() {
            return add(getProxy().createTime());
        }


        @Override
        protected TopicTypeArrayJsonJacksonProxyFetcher createFetcher(TopicTypeArrayJsonJacksonProxy cp, AbstractFetcher<TopicTypeArrayJsonJacksonProxy, TopicTypeArrayJsonJackson, TopicTypeArrayJsonJacksonProxyFetcher> prev, SQLSelectAsExpression sqlSelectExpression) {
            return new TopicTypeArrayJsonJacksonProxyFetcher(cp, this, sqlSelectExpression);
        }
    }


    public static final class Fields {
        public static final String id = "id";
        public static final String stars = "stars";
        public static final String title = "title";
        public static final String title2 = "title2";
        public static final String topicType = "topicType";
        public static final String createTime = "createTime";

        private Fields() {
        }
    }
}
