package com.easy.query.test.entity.relation;


import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link MyRelationUser }
 *
 * @author easy-query
 */
@Data
public class MyRelationUserDTO1 {


    private String id;
    private String name;
    @Navigate(value = RelationTypeEnum.ManyToMany)
    private List<InternalTeachers> teachers;


    /**
     * {@link RelationTeacher }
     */
    @Data
    public static class InternalTeachers {
        private String id;
        private String name;


    }

}
