package com.easy.query.test.h2.domain;


import lombok.Data;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.math.BigDecimal;
import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link TbOrder }
 *
 * @author easy-query
 */
@Data
public class TbOrderDTO {


    private String id;
    private String uid;
    private String uname;
    private BigDecimal price;
    @Navigate(value = RelationTypeEnum.ManyToMany)
    private List<InternalMyAccounts> myAccounts;


    /**
     * {@link TbAccount }
     */
    @Data
    public static class InternalMyAccounts {
        private String id;
        private String uid;
        private String uname;
        private String account;


    }

}
