package com.easy.query.core.proxy.core.tuple.proxy;

import com.easy.query.core.proxy.PropTypeColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.columns.SQLAnyColumn;
import com.easy.query.core.proxy.columns.types.SQLAnyTypeColumn;
import com.easy.query.core.proxy.core.draft.proxy.AbstractDraftProxy;
import com.easy.query.core.proxy.core.tuple.Tuple10;
import com.easy.query.core.proxy.core.tuple.Tuple9;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.util.EasyObjectUtil;

import java.util.Optional;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 *
 * @author xuejiaming
 */
public class Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10> extends AbstractDraftProxy<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, Tuple10<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>> {

    private static final Class<Tuple10> entityClass = Tuple10.class;


    public Tuple10Proxy(PropTypeColumn<T1> column1, PropTypeColumn<T2> column2, PropTypeColumn<T3> column3,
                        PropTypeColumn<T4> column4, PropTypeColumn<T5> column5, PropTypeColumn<T6> column6,
                        PropTypeColumn<T7> column7, PropTypeColumn<T8> column8, PropTypeColumn<T9> column9, PropTypeColumn<T10> column10) {
        super(10);

        fetch(0, column1, "value1");
        fetch(1, column2, "value2");
        fetch(2, column3, "value3");
        fetch(3, column4, "value4");
        fetch(4, column5, "value5");
        fetch(5, column6, "value6");
        fetch(6, column7, "value7");
        fetch(7, column8, "value8");
        fetch(8, column9, "value9");
        fetch(9, column10, "value10");
    }

    /**
     * {@link Tuple10#getValue1}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T1> value1() {
        return getAnyTypeColumn("value1",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[0]).map(o->o.getPropertyType()).orElse(null)));
    }

    /**
     * {@link Tuple10#getValue2()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T2> value2() {
        return getAnyTypeColumn("value2",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[1]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue3()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T3> value3() {
        return getAnyTypeColumn("value3",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[2]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue4()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T4> value4() {
        return getAnyTypeColumn("value4",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[3]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue5()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T5> value5() {
        return getAnyTypeColumn("value5",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[4]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue6()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T6> value6() {
        return getAnyTypeColumn("value6",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[5]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue7()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T7> value7() {
        return getAnyTypeColumn("value7",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[6]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue8()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T8> value8() {
        return getAnyTypeColumn("value8",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[7]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue9()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T9> value9() {
        return getAnyTypeColumn("value9",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[8]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple10#getValue10()}
     */
    public SQLAnyTypeColumn<Tuple10Proxy<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>, T10> value10() {
        return getAnyTypeColumn("value10",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[9]).map(o->o.getPropertyType()).orElse(null)));
    }


    @Override
    public Class<Tuple10<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10>> getEntityClass() {
        return EasyObjectUtil.typeCastNullable(entityClass);
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public Tuple10ProxyFetcher<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10> FETCHER = new Tuple10ProxyFetcher<>(this, null, SQLSelectAsExpression.empty);


    public static class Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> extends AbstractFetcher<Tuple10Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10>, Tuple10<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10>, Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10>> {

        public Tuple10ProxyFetcher(Tuple10Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> proxy, Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * {@link Tuple10#getValue1}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value1() {
            return add(getProxy().value1());
        }


        /**
         * {@link Tuple10#getValue2}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value2() {
            return add(getProxy().value2());
        }
        /**
         * {@link Tuple10#getValue3}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value3() {
            return add(getProxy().value3());
        }
        /**
         * {@link Tuple10#getValue4}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value4() {
            return add(getProxy().value4());
        }
        /**
         * {@link Tuple10#getValue5}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value5() {
            return add(getProxy().value5());
        }
        /**
         * {@link Tuple10#getValue6}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value6() {
            return add(getProxy().value6());
        }
        /**
         * {@link Tuple10#getValue7}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value7() {
            return add(getProxy().value7());
        }
        /**
         * {@link Tuple10#getValue8}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value8() {
            return add(getProxy().value8());
        }

        /**
         * {@link Tuple10#getValue9}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value9() {
            return add(getProxy().value9());
        }
        /**
         * {@link Tuple10#getValue10}
         */
        public Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> value10() {
            return add(getProxy().value10());
        }

        @Override
        protected Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> createFetcher(
                Tuple10Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10> cp,
                AbstractFetcher<Tuple10Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10>, Tuple10<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10>, Tuple10ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8,TF9,TF10>> prev,
                SQLSelectAsExpression sqlSelectExpression
        ) {
            return new Tuple10ProxyFetcher<>(cp, this, sqlSelectExpression);
        }
    }

}
