package com.easy.query.core.proxy.core.tuple.proxy;

import com.easy.query.core.proxy.PropTypeColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.columns.SQLAnyColumn;
import com.easy.query.core.proxy.columns.types.SQLAnyTypeColumn;
import com.easy.query.core.proxy.core.draft.proxy.AbstractDraftProxy;
import com.easy.query.core.proxy.core.tuple.Tuple5;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.util.EasyObjectUtil;

import java.util.Optional;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 *
 * @author xuejiaming
 */
public class Tuple5Proxy<T1,T2,T3,T4,T5> extends AbstractDraftProxy<Tuple5Proxy<T1,T2,T3,T4,T5>, Tuple5<T1,T2,T3,T4,T5>> {

    private static final Class<Tuple5> entityClass = Tuple5.class;


    public Tuple5Proxy(PropTypeColumn<T1> column1, PropTypeColumn<T2> column2, PropTypeColumn<T3> column3, PropTypeColumn<T4> column4, PropTypeColumn<T5> column5) {
        super(5);
        fetch(0, column1, "value1");
        fetch(1, column2, "value2");
        fetch(2, column3, "value3");
        fetch(3, column4, "value4");
        fetch(4, column5, "value5");
    }

    /**
     * {@link Tuple5#getValue1}
     */
    public SQLAnyTypeColumn<Tuple5Proxy<T1,T2,T3,T4,T5>, T1> value1() {
        return getAnyTypeColumn("value1",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[0]).map(o->o.getPropertyType()).orElse(null)));
    }

    /**
     * {@link Tuple5#getValue2()}
     */
    public SQLAnyTypeColumn<Tuple5Proxy<T1,T2,T3,T4,T5>, T2> value2() {
        return getAnyTypeColumn("value2",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[1]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple5#getValue3()}
     */
    public SQLAnyTypeColumn<Tuple5Proxy<T1,T2,T3,T4,T5>, T3> value3() {
        return getAnyTypeColumn("value3",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[2]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple5#getValue4()}
     */
    public SQLAnyTypeColumn<Tuple5Proxy<T1,T2,T3,T4,T5>, T4> value4() {
        return getAnyTypeColumn("value4",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[3]).map(o->o.getPropertyType()).orElse(null)));
    }
    /**
     * {@link Tuple5#getValue5()}
     */
    public SQLAnyTypeColumn<Tuple5Proxy<T1,T2,T3,T4,T5>, T5> value5() {
        return getAnyTypeColumn("value5",EasyObjectUtil.typeCastNullable(Optional.ofNullable(getDraftPropTypes()[4]).map(o->o.getPropertyType()).orElse(null)));
    }


    @Override
    public Class<Tuple5<T1,T2,T3,T4,T5>> getEntityClass() {
        return EasyObjectUtil.typeCastNullable(entityClass);
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public Tuple5ProxyFetcher<T1,T2,T3,T4,T5> FETCHER = new Tuple5ProxyFetcher<>(this, null, SQLSelectAsExpression.empty);


    public static class Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> extends AbstractFetcher<Tuple5Proxy<TF1,TF2,TF3,TF4,TF5>, Tuple5<TF1,TF2,TF3,TF4,TF5>, Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5>> {

        public Tuple5ProxyFetcher(Tuple5Proxy<TF1,TF2,TF3,TF4,TF5> proxy, Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * {@link Tuple5#getValue1}
         */
        public Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> value1() {
            return add(getProxy().value1());
        }


        /**
         * {@link Tuple5#getValue2}
         */
        public Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> value2() {
            return add(getProxy().value2());
        }
        /**
         * {@link Tuple5#getValue3}
         */
        public Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> value3() {
            return add(getProxy().value3());
        }
        /**
         * {@link Tuple5#getValue4}
         */
        public Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> value4() {
            return add(getProxy().value4());
        }
        /**
         * {@link Tuple5#getValue5}
         */
        public Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> value5() {
            return add(getProxy().value5());
        }


        @Override
        protected Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5> createFetcher(
                Tuple5Proxy<TF1,TF2,TF3,TF4,TF5> cp,
                AbstractFetcher<Tuple5Proxy<TF1,TF2,TF3,TF4,TF5>, Tuple5<TF1,TF2,TF3,TF4,TF5>, Tuple5ProxyFetcher<TF1,TF2,TF3,TF4,TF5>> prev,
                SQLSelectAsExpression sqlSelectExpression
        ) {
            return new Tuple5ProxyFetcher<>(cp, this, sqlSelectExpression);
        }
    }

}
