package com.easy.query.test.mysql8.vo;


import com.easy.query.core.annotation.NavigateFlat;
import com.easy.query.core.expression.parser.core.available.MappingPath;
import com.easy.query.test.mysql8.entity.bank.proxy.SysBankCardProxy;
import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;
import com.easy.query.core.annotation.ForeignKey;

import java.time.LocalDateTime;
import java.io.Serializable;

import lombok.Data;

import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.mysql8.entity.bank.SysBankCard }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class SysBankCardDTO {


    private String id;
    private String uid;
    /**
     * 银行卡号
     */
    private String code;
    /**
     * 银行卡类型借记卡 储蓄卡
     */
    private String type;
    /**
     * 所属银行
     */
    private String bankId;
    /**
     * 用户开户时间
     */
    private LocalDateTime openTime;

    private static final MappingPath USER_PHONE_PATH = SysBankCardProxy.TABLE.user().phone();
    @NavigateFlat(pathAlias = "USER_PHONE_PATH")
    private String userPhone;

    private static final MappingPath USER_NAME_PATH = SysBankCardProxy.TABLE.user().name();
    @NavigateFlat(pathAlias = "USER_NAME_PATH")
    private String userName;


}
