package com.easy.query.test.mysql8.vo;


import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.NavigateFlat;
import com.easy.query.test.conversion.StarCodeValueConvert;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.mysql8.entity.bank.SysUser }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class SysUserFirstCardDTO2 {


    private String id;
    private String name;
    private String phone;
    private Integer age;
    private LocalDateTime createTime;


    @NavigateFlat(pathAlias = "firstCard.code")
    @Column(conversion = StarCodeValueConvert.class)
    private String cardCode;
    @NavigateFlat(pathAlias = "firstCard.type")
    private String type;
    @NavigateFlat(pathAlias = "firstCard.openTime")
    private LocalDateTime openTime;


}
