package com.easy.query.test.entity.school.dto;


import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;
import lombok.Data;

import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.school.SchoolClass }
 *
 * @author easy-query
 */
@Data
public class SchoolClassDTO123 {


    private String id;
    private String name;
    //中间表多对多配置,其中mappingClass表示中间表,selfMappingProperty表示中间表的哪个字段和当前表对应,
    //targetMappingProperty表示中间表的哪个字段和目标表的属性对应
    @Navigate(value = RelationTypeEnum.ManyToMany)
    //完整配置其中自己的属性和目标属性忽略表示主键
//    @Navigate(value = RelationTypeEnum.ManyToMany)

    private List<InternalSchoolTeachers> schoolTeachers;


    /**
     * {@link com.easy.query.test.entity.school.SchoolTeacher }
     */
    @Data
    public static class InternalSchoolTeachers {
        private String id;
        private String name;


    }

}
