package com.easy.query.test.mysql8.dto;


import com.easy.query.core.annotation.NavigateFlat;
import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.util.List;
import java.time.LocalDateTime;

import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.mysql8.entity.M8Role }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class M8RoleDTO {


    private String id;
    private String name;
    private LocalDateTime createTime;
    @Navigate(value = RelationTypeEnum.ManyToMany)
    private List<InternalOwner> menus;

    /**
     * {@link com.easy.query.test.mysql8.entity.M8Menu}
     */
    @Data
    public static class InternalOwner {
        @NavigateFlat(pathAlias = "menuOwner.id")
        private String id;
        @NavigateFlat(pathAlias = "menuOwner.name")
        private String name;
    }


}
