package com.easy.query.core.proxy.core.draft.proxy;

import com.easy.query.core.proxy.AbstractProxyEntity;
import com.easy.query.core.proxy.columns.SQLAnyColumn;
import com.easy.query.core.proxy.SQLSelectAsExpression;
import com.easy.query.core.proxy.core.draft.Draft8;
import com.easy.query.core.proxy.fetcher.AbstractFetcher;
import com.easy.query.core.util.EasyObjectUtil;

/**
 * this file automatically generated by easy-query, don't modify it
 * 当前文件是easy-query自动生成的请不要随意修改
 *
 * @author xuejiaming
 */
public class Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8> extends AbstractProxyEntity<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, Draft8<T1,T2,T3,T4,T5,T6,T7,T8>> {

    private static final Class<Draft8> entityClass = Draft8.class;

    public static <TR1,TR2,TR3,TR4,TR5,TR6,TR7,TR8> Draft8Proxy<TR1,TR2,TR3,TR4,TR5,TR6,TR7,TR8> createTable() {
        return new Draft8Proxy<>();
    }

    public Draft8Proxy() {
    }

    /**
     * {@link Draft8#getValue1}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T1> value1() {
        return getAnyColumn("value1",null);
    }

    /**
     * {@link Draft8#getValue2()}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T2> value2() {
        return getAnyColumn("value2",null);
    }
    /**
     * {@link Draft8#getValue3()}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T3> value3() {
        return getAnyColumn("value3",null);
    }
    /**
     * {@link Draft8#getValue4()}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T4> value4() {
        return getAnyColumn("value4",null);
    }
    /**
     * {@link Draft8#getValue5()}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T5> value5() {
        return getAnyColumn("value5",null);
    }
    /**
     * {@link Draft8#getValue6()}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T6> value6() {
        return getAnyColumn("value6",null);
    }
    /**
     * {@link Draft8#getValue7()}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T7> value7() {
        return getAnyColumn("value7",null);
    }
    /**
     * {@link Draft8#getValue8()}
     */
    public SQLAnyColumn<Draft8Proxy<T1,T2,T3,T4,T5,T6,T7,T8>, T8> value8() {
        return getAnyColumn("value8",null);
    }


    @Override
    public Class<Draft8<T1,T2,T3,T4,T5,T6,T7,T8>> getEntityClass() {
        return EasyObjectUtil.typeCastNullable(entityClass);
    }


    /**
     * 数据库列的简单获取
     *
     * @return
     */
    public Draft8ProxyFetcher<T1,T2,T3,T4,T5,T6,T7,T8> FETCHER = new Draft8ProxyFetcher<>(this, null, SQLSelectAsExpression.empty);


    public static class Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> extends AbstractFetcher<Draft8Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8>, Draft8<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8>, Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8>> {

        public Draft8ProxyFetcher(Draft8Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> proxy, Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> prev, SQLSelectAsExpression sqlSelectAsExpression) {
            super(proxy, prev, sqlSelectAsExpression);
        }


        /**
         * {@link Draft8#getValue1}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value1() {
            return add(getProxy().value1());
        }


        /**
         * {@link Draft8#getValue2}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value2() {
            return add(getProxy().value2());
        }
        /**
         * {@link Draft8#getValue3}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value3() {
            return add(getProxy().value3());
        }
        /**
         * {@link Draft8#getValue4}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value4() {
            return add(getProxy().value4());
        }
        /**
         * {@link Draft8#getValue5}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value5() {
            return add(getProxy().value5());
        }
        /**
         * {@link Draft8#getValue6}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value6() {
            return add(getProxy().value6());
        }
        /**
         * {@link Draft8#getValue7}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value7() {
            return add(getProxy().value7());
        }
        /**
         * {@link Draft8#getValue8}
         */
        public Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> value8() {
            return add(getProxy().value8());
        }


        @Override
        protected Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> createFetcher(
                Draft8Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8> cp,
                AbstractFetcher<Draft8Proxy<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8>, Draft8<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8>, Draft8ProxyFetcher<TF1,TF2,TF3,TF4,TF5,TF6,TF7,TF8>> prev,
                SQLSelectAsExpression sqlSelectExpression
        ) {
            return new Draft8ProxyFetcher<>(cp, this, sqlSelectExpression);
        }
    }

}
