package com.easy.query.test.dto.autodto;


import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.annotation.NavigateFlat;
import com.easy.query.core.enums.RelationTypeEnum;
import com.easy.query.test.entity.school.SchoolClass;
import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.school.SchoolStudent }
 *
 * @author easy-query
 */
@Data
public class SchoolStudentDTOxxx {


    private String id;
    private String classId;
    private String name;
    @NavigateFlat(pathAlias = "schoolClass.name")
    private String schoolClassName;
    //    private Integer age;
    @Navigate(value = RelationTypeEnum.ManyToOne)
    private SchoolClass schoolClass;
    @Navigate(value = RelationTypeEnum.OneToOne)
    private InternalSchoolStudentAddress schoolStudentAddress;


    /**
     * {@link com.easy.query.test.entity.school.SchoolClass }
     */
    @Data
    public static class InternalSchoolClass {
        private String id;
        private String name;


    }


    /**
     * {@link com.easy.query.test.entity.school.SchoolStudentAddress }
     */
    @Data
    public static class InternalSchoolStudentAddress {
        private String id;
        private String studentId;
        private String address;


    }

}
