package com.easy.query.test.dto.autodto;


import com.easy.query.core.annotation.NavigateFlat;
import com.easy.query.core.expression.parser.core.available.MappingPath;
import com.easy.query.test.entity.school.proxy.SchoolStudentProxy;
import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.school.SchoolStudent }
 *
 * @author easy-query
 */
@Data
public class SchoolStudentDTOAO111 {


    @Column(value = "EasyStringUtil.EMPTY")
    private String id;
    private String classId;
    private String name;
    private static final MappingPath ADDRESS_PATH = SchoolStudentProxy.TABLE.schoolStudentAddress().address();
    @NavigateFlat(pathAlias = "ADDRESS_PATH")private String address;
    //    private Integer age;
    @Navigate(value = RelationTypeEnum.ManyToOne)
    private InternalSchoolClass schoolClass;


    /**
     * {@link com.easy.query.test.entity.school.SchoolClass }
     */
    @Data
    public static class InternalSchoolClass {
        @Column(value = "EasyStringUtil.EMPTY")//主键
        private String id;
        private String name;


    }

}
