package com.easy.query.test.doc.dto;


import com.easy.query.core.annotation.EntityProxy;
import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.doc.entity.DocUser }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: normal
 */
@Data
//@SuppressWarnings("EasyQueryFieldMissMatch")
@EntityProxy
public class DocUserVO {


    private String id;
    private String name;
    private String phone;
    private Integer age;

    @SuppressWarnings("EasyQueryFieldMissMatch")
    private Long cardCount;

}
