package com.easy.query.test.doc.dto;


import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.time.LocalDateTime;
import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.doc.MyComUser }
 *
 * @author easy-query
 */
@Data
public class MyComUserDTO1 {


    private String id;
    private String comId;
    private String userId;
    private String gw;
    @Navigate(value = RelationTypeEnum.OneToMany)
    private List<InternalMySignUps> mySignUps;
    @Navigate(value = RelationTypeEnum.ManyToOne)
    private InternalMyCompany myCompany;
    @Navigate(value = RelationTypeEnum.ManyToOne)
    private InternalMyUser myUser;


    /**
     * {@link com.easy.query.test.doc.MySignUp }
     */
    @Data
    public static class InternalMySignUps {
        private String id;
        private String comId;
        private String userId;
        private LocalDateTime time;
        private String content;


    }


    /**
     * {@link com.easy.query.test.doc.MyCompany }
     */
    @Data
    public static class InternalMyCompany {
        private String id;
        private String name;


    }


    /**
     * {@link com.easy.query.test.doc.MyUser }
     */
    @Data
    public static class InternalMyUser {
        private String id;
        private String name;
        private Integer age;


    }

}
