package com.easy.query.test.doc.dto;


import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.doc.MySignUp }
 * @easy-query-dto schema: normal
 *
 * @author xuejiaming
 */
@Data
public class MySignUpDTO2 {


    private String id;
    private String comId;
    private String userId;
    private LocalDateTime time;
    private String content;
    @Navigate(value = RelationTypeEnum.ManyToOne)
    private InternalComUserCompany comUserCompany;


    /**
     * {@link com.easy.query.test.doc.MyCompany }
     *
     */
    @Data
    public static class InternalComUserCompany {

        private String id;
        private String name;


    }

}
