package com.easy.query.test.testvo;


import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;
import lombok.Data;

import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.entity.school.SchoolClass }
 *
 * @author easy-query
 */
@Data
public class SchoolClassDTO {


    private String id;
    private String name;
    //一对多 一个班级多个学生
    @Navigate(value = RelationTypeEnum.OneToMany)
    //完整配置,property忽略表示对应的主键
//    @Navigate(value = RelationTypeEnum.OneToMany)
    private List<SchoolClassDTO_SchoolStudent0> schoolStudents;


    /**
     * {@link com.easy.query.test.entity.school.SchoolStudent }
     */
    @Data
    public static class SchoolClassDTO_SchoolStudent0 {
        private String id;
        private String classId;
        private String name;
        @Navigate(value = RelationTypeEnum.OneToOne)
        private SchoolClassDTO_SchoolStudentAddress1 schoolStudentAddress;


    }


    /**
     * {@link com.easy.query.test.entity.school.SchoolStudentAddress }
     */
    @Data
    public static class SchoolClassDTO_SchoolStudentAddress1 {
        private String id;
        private String studentId;
        private String address;
        @Navigate(value = RelationTypeEnum.ManyToOne)
        private SchoolClassDTO_SchoolStudent2 schoolStudent;


    }


    /**
     * {@link com.easy.query.test.entity.school.SchoolStudent }
     */
    @Data
    public static class SchoolClassDTO_SchoolStudent2 {
        private String id;
        private String classId;
        private String name;

    }

}
