package com.easy.query.test.dameng.vo;


import lombok.Data;
import com.easy.query.core.annotation.Column;
import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.dameng.entity.DamengNameCustom }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class DamengNameCustomDTO {


    private String id;
    private String name;
    private Integer rowNumber;
    private Integer isDelete;


}
