package com.easy.query.test.doc;


import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.util.List;

import lombok.Data;
import lombok.experimental.FieldNameConstants;

import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link MyComUser }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
@FieldNameConstants
public class MyComUserDTO {


    private String id;
    private String comId;
    private String userId;
    private String gw;
    private String gwName;
    @Navigate(value = RelationTypeEnum.OneToMany)
    private List<InternalMySignUps> mySignUps;


    /**
     * {@link MySignUp }
     */
    @Data
    public static class InternalMySignUps {

        private String id;
        private String comId;
        private String userId;
        private LocalDateTime time;
        private String content;


    }

}
